### ISSUE TITLE
Extraction is very slow?

### ISSUE THREAD

**Issue by txntxn** [swisscom/ai-research-keyphrase-extraction#21]
I am running extraction on short sentences, roughly 20 words.

I have followed your instructions to load the embedding model and the part of speech tagger once.

However, it takes about 3 seconds per extraction on a dedicated machine.

Is this expected? How can I make extraction faster?

**Comment by kamilbs** [comment]
On which language ?

**Comment by txntxn** [comment]
English.

**Comment by kamilbs** [comment]
The bottleneck is certainly due to the pos tagging. 
You can check that it's actually the bottleneck by trying the following `pos_tagger.pos_tag_raw_text(your_text)`. 

As you can see [here](https://github.com/swisscom/ai-research-keyphrase-extraction/blob/6c4479954f9b98cc0b8e49324f1ca5945aa81405/swisscom_ai/research_keyphrase/preprocessing/postagging.py#L130 ) in the provided code we rely on StanfordPosTagger implementation of nltk  for convenience  https://www.nltk.org/_modules/nltk/tag/stanford.html which is not ideal if you want a fast extraction.

In order to make extraction faster I'll suggest you to create your own PosTagger that follows our PosTagging [interface](https://github.com/swisscom/ai-research-keyphrase-extraction/blob/6c4479954f9b98cc0b8e49324f1ca5945aa81405/swisscom_ai/research_keyphrase/preprocessing/postagging.py#L23)  by implementing the `pos_tag_raw_text` method and ensure that this PosTagger remains available and ready for online predictions. 

One possibility that should be fast to implement and try is to create a PosTagging class that makes calls to a [Core NLP Server ](https://stanfordnlp.github.io/CoreNLP/corenlp-server.html)

**Comment by kamilbs** [comment]
Solved with #25

**Comment by pbeneteau** [comment]
> I am running extraction on short sentences, roughly 20 words.
> 
> I have followed your instructions to load the embedding model and the part of speech tagger once.
> 
> However, it takes about 3 seconds per extraction on a dedicated machine.
> 
> Is this expected? How can I make extraction faster?

Did you manage to improve the extraction time? Because on my server, the extraction takes 2 minutes with a 16gb pre-trained model file.
